### PR TITLE
fix rollup

### PR DESCRIPTION
**Pull request by makc**
before:
изображение

after:
изображение

### CODE REVIEW

**Comment by makc** [comment]
same in main folder, before:
изображение

after:
изображение

**Comment by aka-blackboots** [comment]
Hey @makc, I'm testing this PR. The build is failing on `npm run build`

**Comment by makc** [comment]
> There are few new changes that were added to the repo since this PR.

yes, this is quite possible. it did fix a build for me two months ago, but I did not update ever since then. My best guess is that the problem still exists in some form (since nobody noticed it or cared about it back then, they could not have intentionally fix it either), but... it will have to wait for some other time.

**Comment by aka-blackboots** [comment]
this commit 26638527d505eb3787173b0ad43e007d745a0e88 will fix the issue you were facing, thanks for addressing it!

**Pull request closed without merging**
